### ISSUE TITLE
Not found module : error

### ISSUE THREAD

**Issue by Abhi035** [Asymmetrik/node-fhir-server-core#237]
Running local host on 3000; while POST request using api (http://localhost:3000/connect/token), getting below error:

<pre>Error: Cannot find module &#39;D:\node-fhir-server-core\src\server\resources\connect\schemas\operationoutcome&#39;<br> &nbsp; &nbsp;at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)<br> &nbsp; &nbsp;at Function.Module._load (internal/modules/cjs/loader.js:508:25)<br> &nbsp; &nbsp;at Module.require (internal/modules/cjs/loader.js:637:17)<br> &nbsp; &nbsp;at require (internal/modules/cjs/helpers.js:22:18)<br> &nbsp; &nbsp;at app.use (D:\node-fhir-server-core\src\server\server.js:282:27)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\node-fhir-server-core\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (D:\node-fhir-server-core\node_modules\express\lib\router\index.js:317:13)<br> &nbsp; &nbsp;at D:\node-fhir-server-core\node_modules\express\lib\router\index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (D:\node-fhir-server-core\node_modules\express\lib\router\index.js:335:12)<br> &nbsp; &nbsp;at next (D:\node-fhir-server-core\node_modules\express\lib\router\index.js:275:10)</pre>

Can anyone help me to solve this issue? I need it urgently. Thanks in advance.

**Comment by sychus** [comment]
Hi Abhi035!

could you explain what you are trying to do? Maybe I can help you with your problem.

Cheers!

**Comment by zeevosec** [comment]
I'm closing this due to inactivity! Feel free to reopen if this is an issue.
