### ISSUE TITLE
BundleEntry.js - Resource does not inherit from ("./Resource") and cannot call toJSON

### ISSUE THREAD

**Issue by dominathan** [Asymmetrik/node-fhir-server-core#80]
### Are you reporting a bug?
Yes.

**What is the current behavior?**
I am hitting `http://localhost:3001/3_0_1/Medication?_content=ritalin`.  Here is the data I pass into my `resolve()`.

```
[{"resourceType":"Medication","id":"13424","meta":{"lastUpdated":"stuff"},"code":{"text":"8 HR Metadate 20 MG Extended Release Oral Tablet","coding":[{"system":"http://www.nlm.nih.gov/research/umls/rxnorm","code":"1091488","display":"8 HR Metadate 20 MG Extended Release Oral Tablet","userSelected":false}]},"isBrand":true,"isOverTheCounter":false,"form":"tablet"},{"resourceType":"Medication","id":"13424","meta":{"lastUpdated":"stuff"},"code":{"text":"Ritalin 5 MG Oral Tablet","coding":[{"system":"http://www.nlm.nih.gov/research/umls/rxnorm","code":"1091500","display":"Ritalin 5 MG Oral Tablet","userSelected":false}]},"isBrand":true,"isOverTheCounter":false,"form":"tablet"}]
```

The response from the server

```
{ message: 'this.__resource.toJSON is not a function',
  stack: 'TypeError: this.__resource.toJSON is not a function\n    at BundleEntry.toJSON 

(/Users/nhall/common-clinical/fdb-proxy/node_modules/@asymmetrik/node-fhir-server-core/src/server/standards/3_0_1/BundleEntry.js:72:49)\n    
at Object.assign.entry.__entry.__entry.map.v (/Users/nhall/common-clinical/fdb-proxy/node_modules/@asymmetrik/node-fhir-server-core/src/server/standards/3_0_1/Bundle.js:96:51)\n    
at Array.map (<anonymous>)\n    at Bundle.toJSON (/Users/nhall/common-clinical/fdb-proxy/node_modules/@asymmetrik/node-fhir-server-core/src/server/standards/3_0_1/Bundle.js:96:40)\n    
at JSON.stringify (<anonymous>)\n   
at stringify (/Users/nhall/common-clinical/fdb-proxy/node_modules/express/lib/response.js:1119:12)\n 
   at ServerResponse.json (/Users/nhall/common-clinical/fdb-proxy/node_modules/express/lib/response.js:260:14)\n    
at Object.handleBundleReadResponse (/Users/nhall/common-clinical/fdb-proxy/node_modules/@asymmetrik/node-fhir-server-core/src/server/utils/response.utils.js:103:18)\n  
at service.search.then (/Users/nhall/common-clinical/fdb-proxy/node_modules/@asymmetrik/node-fhir-server-core/src/server/profiles/medication/medication.controller.js:48:19)\n   
 at <anonymous>' }
```

The issue I think is in `src/server/standards/3_0_1/BundleEntry.js`.  If you look at the setters, it is not requiring `./Resource` to instantiate a new object, and not inheriting toJSON.  The options are
1. `require('./Resource')` on line 36 and instantiate a new resource object
2. remove `toJSON` on line 73.

In my pull request, I went with option 2 because it works for my use case.   It now returns 

```
{
  resourceType: "Bundle",
  type: "searchset",
  total: 2,
  link: [
    {
      relation: "self",
      url: "http://localhost:3001/3_0_1/Medication?_content=ritalin"
    }
  ],
  entry: [
    {
      fullUrl: "undefined/3_0_1/Medication/13424",
      resource: {
        resourceType: "Medication",
        id: "13424",
        meta: {
          lastUpdated: "stuff"
        },
        code: {
          text: "8 HR Metadate 20 MG Extended Release Oral Tablet",
          coding: [
            {
              system: "http://www.nlm.nih.gov/research/umls/rxnorm",
              code: "1091488",
              display: "8 HR Metadate 20 MG Extended Release Oral Tablet",
              userSelected: false
            }
          ]
        },
        isBrand: true,
        isOverTheCounter: false,
        form: "tablet"
      },
      search: {
        mode: "match"
      }
    },
    {
      ...truncated other object
    }
  ]
}
```

I'll submit the pull request as well.  Test and lint all pass.  Please let me know if I'm in error.   Thanks again for this great project.

**Comment by dominathan** [comment]
For more clarity, if I go with option 1 and change the setter to
```js
	set resource(new_value) {
		const Resource = require('./Resource')
		this.__resource = new Resource(new_value)
	}
```

Then the response cuts out the Medication as shown below.
```
{
  resourceType: "Bundle",
  type: "searchset",
  total: 2,
  link: [
    {
      relation: "self",
      url: "http://localhost:3001/3_0_1/Medication?_content=ritalin"
    }
  ],
  entry: [
    {
      fullUrl: "undefined/3_0_1/Medication/13424",
      resource: {
        resourceType: "Resource",
        id: "13424",
        meta: {
          lastUpdated: "stuff"
        }
      },
      search: {
        mode: "match"
      }
    },
    {
        fullUrl: "undefined/3_0_1/Medication/13425",
      // trruncated
```

**Comment by jonterrylee** [comment]
Thanks @dominathan Option 1 is preferred.  These resources are auto generated from the Structure definitions and we've attempted to test as much as we could.

We're going to update the generator to fix this issue as well.  If you could submit a PR for the small change, that would be very helpful for the time being.


Also - If there are other versions of STU3/DSTU2 that you would like to support, please let us know.  We're hoping to have R4 and US CORE out shortly as well.

**Comment by jonterrylee** [comment]
@dominathan 

Sorry we did more research into this issue and we realized what your issue may be.

When you pass back the JSON from the services, they need to be casted to a resource first.

If you take a look at the example Mongo Library, it shows how it works.
https://github.com/Asymmetrik/node-fhir-server-mongo/blob/master/src/services/patient/patient.service.js 

In your case:
`
SearchMedications () {

		data.toArray().then((medications) => {
			medications.forEach(function(element, i, returnArray) {
				returnArray[i] = new Medication(element);
			});
			resolve(medications);
		});
}

`

**Comment by dominathan** [comment]
Nice.  I was doing some Joi library validations and passing it along.  Thanks for the quick responses, I'll try that out and see if it resolves it.

**Comment by dominathan** [comment]
Alright, so I am doing this.

```js
const Joi = require("joi")
const FHIRServer = require("@asymmetrik/node-fhir-server-core")

const getMedication = _ => {
	return require(FHIRServer.resolveFromVersion("3_0_1", "Medication"))
}

const Medication = getMedication()

const schemaForMedication = Joi.object({
	resourceType: Joi.string()
		.valid("Medication")
		.required(),
	meta: Joi.object(),
	id: Joi.string().required(),
	code: Joi.object({
		text: Joi.string().required(),
		coding: Joi.array().items(
			Joi.object({
				system: Joi.string().required(),
				version: Joi.string(),
				code: Joi.string().required(),
				display: Joi.string().required(),
				userSelected: Joi.boolean()
			})
		)
	}),
	isBrand: Joi.boolean(),
	isOverTheCounter: Joi.boolean(),
	manufacturer: Joi.any(), // TODO: need to double check this, says it is a reference https://www.hl7.org/fhir/medication.html,
	form: Joi.any(), // TODO: need to double check this, says it is a reference https://www.hl7.org/fhir/medication.html,
	ingredient: Joi.any(), // TODO: need to double check this, says it is a reference https://www.hl7.org/fhir/medication.html,
	package: Joi.any() // TODO: need to double check this, says it is a reference https://www.hl7.org/fhir/medication.html,
})

const fhirConverted = fdbMedicationList => {
	return fdbMedicationList.map(fdbMed => {
		const fhirMed = {
			resourceType: "Medication",
			id: "13424",
			meta: {
				lastUpdated: "stuff"
			},
			code: {
				text: fdbMed.RXCUIDesc,
				coding: [
					{
						system: "http://www.nlm.nih.gov/research/umls/rxnorm",
						code: fdbMed.RXCUI,
						display: fdbMed.RXCUIDesc, // is this the right display name?
						userSelected: false // what is this?
					}
				]
			},
			isBrand: fdbMed.NameTypeCode === "1" ? true : false,
			isOverTheCounter: false // Where do i get this info
			//manufacturer: {}, // does not seem to be provided by the route we currently hit with searchErxDispensableDrug
			// form: fdbMed.ClinicalQuantity.ClinicalQuantityDesc.toLowerCase()
			//ingredient: {},
			//package: {} // not surre where to get this info
		}

		const { error, value } = Joi.validate(fhirMed, schemaForMedication)
		if (error) {
			return error
		}

		let med = new Medication(value)
		return med
	})
}

module.exports = fhirConverted

```

An example Medication now comes back instantiated.

<img width="859" alt="screen shot 2018-09-27 at 11 03 56 am" src="https://user-images.githubusercontent.com/6124206/46155359-1c696000-c245-11e8-96c0-303e140970d9.png">

And has an Array of Medications as the resource_json.  I get the same error if I do not change `BundleEntry`.  If I change `BundleEntry` to Option 1, then the Medication gets removed from the response. 
<img width="499" alt="screen shot 2018-09-27 at 11 06 12 am" src="https://user-images.githubusercontent.com/6124206/46155491-6d795400-c245-11e8-857d-9a37d4268a88.png">

If I change it to option 2, it returns everything as I desire.  I might be passing things in that I need that are not  being included but I am not sure.

Side note, are you going to the HL7 conference this Saturday-Friday in Baltimore? @jonterrylee

**Comment by jonterrylee** [comment]
let me pull this down and try it out.  

A few of us are at the HL7 app conference today and tomorrow.  A few of us will be at the conference on Monday in Baltimore.  Are you going to be there as well?

**Comment by dominathan** [comment]
Me and a few people will be in Baltimore for the hackathon this weekend and then the conference.  Would love to buy y'all some drinks.

**Comment by jonterrylee** [comment]
@dominathan 

Hey, I was able to get your example to work.  I didn't make any changes to the Bundle or core lib.  I checked in the branch so you can take a look.
https://github.com/Asymmetrik/node-fhir-server-mongo/tree/example/medication-joi
using docker
 - run `docker-compose build`
 - run `docker-compose up`

my changes:
medication.service.js
```javascript
et getMedication = (base_version) => {
	return require(FHIRServer.resolveFromVersion(base_version, RESOURCES.MEDICATION));};

let getMeta = (base_version) => {
	return require(FHIRServer.resolveFromVersion(base_version, RESOURCES.META));};


let MED_DATA = [
	{
		"resourceType": "Medication",
		"id": "13424",
		"meta": {
			"lastUpdated": "stuff"
		},
		"code": {
			"text": "8 HR Metadate 20 MG Extended Release Oral Tablet",
			"coding": [{
				"system": "http://www.nlm.nih.gov/research/umls/rxnorm",
				"code": "1091488",
				"display": "8 HR Metadate 20 MG Extended Release Oral Tablet",
				"userSelected": false
			}]
		},
		"isBrand": true,
		"isOverTheCounter": false,
		"form": "tablet"
	}, {
		"resourceType": "Medication",
		"id": "13424",
		"meta": {
			"lastUpdated": "stuff"
		},
		"code": {
			"text": "Ritalin 5 MG Oral Tablet",
			"coding": [{
				"system": "http://www.nlm.nih.gov/research/umls/rxnorm",
				"code": "1091500",
				"display": "Ritalin 5 MG Oral Tablet",
				"userSelected": false
			}]
		},
		"isBrand": true,
		"isOverTheCounter": false,
		"form": "tablet"
	}
]

const schemaForMedication = Joi.object({
	resourceType: Joi.string()
		.valid("Medication")
		.required(),
	meta: Joi.object(),
	id: Joi.string().required(),
	code: Joi.object({
		text: Joi.string().required(),
		coding: Joi.array().items(
			Joi.object({
				system: Joi.string().required(),
				version: Joi.string(),
				code: Joi.string().required(),
				display: Joi.string().required(),
				userSelected: Joi.boolean()
			})
		)
	}),
	isBrand: Joi.boolean(),
	isOverTheCounter: Joi.boolean(),
	manufacturer: Joi.any(), // TODO: need to double check this, says it is a reference https://www.hl7.org/fhir/medication.html,
	form: Joi.any(), // TODO: need to double check this, says it is a reference https://www.hl7.org/fhir/medication.html,
	ingredient: Joi.any(), // TODO: need to double check this, says it is a reference https://www.hl7.org/fhir/medication.html,
	package: Joi.any() // TODO: need to double check this, says it is a reference https://www.hl7.org/fhir/medication.html,
})


const fhirConverted = fdbMedicationList => {

	let Medication = getMedication('3_0_1');

	return fdbMedicationList.map(fdbMed => {

		const { error, value } = Joi.validate(fdbMed, schemaForMedication)
		if (error) {
			return error
		}

		let med = new Medication(value)
		return med
	})
}

module.exports.search = (args, context, logger) => new Promise((resolve, reject) => {
	logger.info('Medication >>> search');

	let medications = fhirConverted(MED_DATA);

	// Return Array
	resolve(medications);
});
```

results
<img width="620" alt="screen shot 2018-09-27 at 1 49 28 pm" src="https://user-images.githubusercontent.com/12969956/46164533-3b272100-c25c-11e8-9e63-576f2b6ae00e.png">

You may have another issue.  If you can make a repo, we'll be sure to help you out.


Definitely should grab some drinks!  We can try to aim for the weekend or Monday would work as well.

**Comment by andrewmarcus** [comment]
> Me and a few people will be in Baltimore for the hackathon this weekend and then the conference. Would love to buy y'all some drinks.

Hi @dominathan, we won't be able to send anybody to the hackathon, unfortunately, but I'll be at the Working Group all week.  Shoot me an email and let's connect, amarcus@asymmetrik.com

**Comment by dominathan** [comment]
Yea,I don't know what happened.  Must have made too many edits to the package.  Deleted it and worked fine.   Sorry about that.  Thanks for your help!

I'll respond to your email @andrewmarcus .  Definitely owe you all for putting this project together.
