### ISSUE TITLE
Server will not start on Ubuntu 16.04 when trying to grab capitalized argument file.

### ISSUE THREAD

**Issue by dominathan** [Asymmetrik/node-fhir-server-core#91]
### Are you reporting a bug?
Yes
**What is the current behavior?**
Trying to start server on an ubuntu 16.04 does not work because filenames are case sensitive but the `/server/utils/params.utils.js:23` uses a lowercase profilekey.
**What is the expected behavior?**
Grab the allowed arguments for the profiles specified.
**What are the steps to reproduce?**
Try to start a server on ubuntu 16.04
**What OS are you using and what version of node.js and @asymmetrik/fhir-server-core are you running?**
ubuntu 16.04 / node 8.11.2 / node-fhir-server-core master

```
2018-10-11T14:16:08.74-0400 [APP/PROC/WEB/0] ERR Error: Cannot find module '../standards/3_0_1/arguments/allergyintolerance.arguments'
2018-10-11T14:16:08.74-0400 [APP/PROC/WEB/0] ERR     ^
2018-10-11T14:16:08.74-0400 [APP/PROC/WEB/0] ERR     at configureResourceRoutes (/home/vcap/deps/0/node_modules/@asymmetrik/node-fhir-server-core/src/server/route-setter.js:151:20)
2018-10-11T14:16:08.74-0400 [APP/PROC/WEB/0] ERR     at Object.setter [as setRoutes] (/home/vcap/deps/0/node_modules/@asymmetrik/node-fhir-server-core/src/server/route-setter.js:278:2)
2018-10-11T14:16:08.74-0400 [APP/PROC/WEB/0] ERR     at getSearchParamaters (/home/vcap/deps/0/node_modules/@asymmetrik/node-fhir-server-core/src/server/utils/params.utils.js:23:33)
2018-10-11T14:16:08.74-0400 [APP/PROC/WEB/0] ERR     at Function.Module._resolveFilename (module.js:547:15)
2018-10-11T14:16:08.74-0400 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:474:25)
2018-10-11T14:16:08.74-0400 [APP/PROC/WEB/0] ERR     at require (internal/module.js:11:18)
2018-10-11T14:16:08.74-0400 [APP/PROC/WEB/0] ERR     at Array.forEach (<anonymous>)
2018-10-11T14:16:08.74-0400 [APP/PROC/WEB/0] ERR     at profile.versions.forEach.version (/home/vcap/deps/0/node_modules/@asymmetrik/node-fhir-server-core/src/server/route-setter.js:152:30)
2018-10-11T14:16:08.75-0400 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
2018-10-11T14:16:08.75-0400 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
2018-10-11T14:16:08.75-0400 [APP/PROC/WEB/0] ERR npm ERR! fdb-proxy@0.0.1 start: `node server.js`
2018-10-11T14:16:08.75-0400 [APP/PROC/WEB/0] ERR npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-10-11T14:16:08.75-0400 [APP/PROC/WEB/0] ERR npm ERR! Failed at the fdb-proxy@0.0.1 start script.
2018-10-11T14:16:08.83-0400 [APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/.npm/_logs/2018-10-11T18_16_08_760Z-debug.log
2018-10-11T14:16:08.83-0400 [APP/PROC/WEB/0] ERR npm ERR! A complete log of this run can be found in:
```

Potential Fix is #90

**Comment by jonterrylee** [comment]
@dominathan 

We've also recently found this issue when running in Docker (Linux).  The team was trying to decide which convention to stick with going forward.  I believe we're ultimately going with the lowercase file names for the standards and arguments.  I think your fix is great and is a good check especially since these files are auto generated.

**Comment by dominathan** [comment]
Resolved
