### ISSUE TITLE
resolve.utils breaks on case sensitive operating systems

### ISSUE THREAD

**Issue by dominathan** [Asymmetrik/node-fhir-server-core#93]
### Are you reporting a bug?
Yes
### What is the current behavior?
Trying to start server on an ubuntu 16.04 does not work because filenames are case sensitive but the /server/utils/resolve.utils.js:6 uses a lowercase relative_path with key.
### What is the expected behavior?
Grab the allowed arguments for the relative_path specified.
### What are the steps to reproduce?
Try to start a server on ubuntu 16.04
### What OS are you using and what version of node.js and @asymmetrik/fhir-server-core are you running?
ubuntu 16.04 / node 8.11.2 / node-fhir-server-core master

```
info: Metadata.generateCapabilityStatement
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR 2018-10-12T13:52:46.270Z - error: 500 message=Cannot find module '/home/vcap/deps/0/node_modules/@asymmetrik/node-fhir-server-core/src/server/standards/3_0_1/medication', stack=Error: Cannot find module '/home/vcap/deps/0/node_modules/@asymmetrik/node-fhir-server-core/src/server/standards/3_0_1/medication'
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR     at Function.Module._resolveFilename (module.js:547:15)
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:474:25)
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR     at Module.require (module.js:596:17)
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR     at require (internal/module.js:11:18)
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR     at Object.resource [as makeResource] (/home/vcap/deps/0/node_modules/@asymmetrik/node-fhir-server-core/src/server/metadata/capability.template.js:11:18)
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR     at server_statement.resource.active_profiles.map (/home/vcap/deps/0/node_modules/@asymmetrik/node-fhir-server-core/src/server/metadata/metadata.service.js:69:12)
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR     at Array.map (<anonymous>)
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR     at Promise (/home/vcap/deps/0/node_modules/@asymmetrik/node-fhir-server-core/src/server/metadata/metadata.service.js:66:46)
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR     at new Promise (<anonymous>)
2018-10-12T09:52:46.27-0400 [APP/PROC/WEB/0] ERR     at Object.generateCapabilityStatement (/home/vcap/deps/0/node_modules/@asymmetrik/node-fhir-server-core/src/server/metadata/metadata.service.js:24:61), code=MODULE_NOT_FOUND
```
Potential Fix is #92

**Comment by dominathan** [comment]
Resolved
